remote_theme: pages-themes/slate@v0.2.0

plugins:
- jekyll-remote-theme 

title: Hugo Rosário
description: Hello there, welcome to my personal website.\nA place to share projects and ideas I explore once in a while. 